### ISSUE TITLE
Docker Compose Example Path

### ISSUE THREAD

**Issue by tcallsen** [ckulka/infcloud-docker#3]
Hi,

Thank you very much for posting this image. I am using it to host an instance of InfCloud and its working great.

I did have to change one line on the Docker Compose sample file and thought I'd call it out in case it might help others.

I had to update the container mount point on the line referenced below to:

`/host/os/config.js:/usr/share/nginx/infcloud/config.js:ro` 

https://github.com/ckulka/infcloud-docker/blob/692b9b879576f0f1f1a2da3385ea35ae850d9fb2/examples/docker-compose.yaml#L13

Happy to open a PR if it'd be worth it.

Take care and thanks again,

Taylor

**Comment by ckulka** [comment]
Thanks @tcallsen ! Definitively worth fixing, but no need to go through the trouble of forking and PR'ing, just pushed an update to fix the example.
