### ISSUE TITLE
Unnecessary volume mount

### ISSUE THREAD

**Issue by origonn** [ckulka/infcloud-docker#4]
The volume mount set in the Dockerfile seems unnecessary (/usr/share/nginx/html) as /usr/share/nginx/infcloud is used to serve the actual application. This creates an anonymous volume by default, as this volume isn't mentioned in any docs / docker-compose. This could probably be removed as a docker volume, since it holds only default nginx pages and does not really need to be persisted into a volume. 

https://github.com/ckulka/infcloud-docker/blob/master/Dockerfile#L18

**Comment by ckulka** [comment]
Good point, I'll take it out 👍

**Comment by ckulka** [comment]
Should done done, let me know if it didn't work out
