### ISSUE TITLE
Update Baikal Nginx Example

### ISSUE THREAD

**Issue by origonn** [ckulka/infcloud-docker#5]
Hello, with the recent Baikal update to php 8.1, the example baikal nginx config no longer works as it points to a 7.4 php 

https://github.com/ckulka/infcloud-docker/blob/master/examples/baikal-nginx.conf#L30

Should be updated to /var/run/php-fpm.sock to work

**Comment by ckulka** [comment]
Good catch... given this might change more often as PHP is updated, I'll update the example with directives on where to find the correct value.
